ALTER TABLE public.sellers ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE public.sellers ADD COLUMN IF NOT EXISTS location_link TEXT;
ALTER TABLE public.sellers ADD COLUMN IF NOT EXISTS latitude DECIMAL(10, 7);
ALTER TABLE public.sellers ADD COLUMN IF NOT EXISTS longitude DECIMAL(10, 7);
